# /mnt/d/activity/auth-api/app/routes/twofa.py
from fastapi import APIRouter, Depends, status, Header
from app.services.two_factor_service import TwoFactorService
from app.services.token_service import TokenService
from app.schemas.auth import TwoFactorVerifyRequest

router = APIRouter()

# Note: These endpoints should be protected by a valid access token.
# This assumes a dependency injection system for authentication.
# For simplicity, we'll manually extract user_id from the token.

async def get_current_user_id(
    authorization: str = Header(),
    token_service: TokenService = Depends(TokenService)
) -> int:
    """A dependency to get user ID from Authorization header."""
    token = authorization.split(" ")[1]
    user_id = token_service.get_user_id_from_token(token, "access")
    return user_id


@router.post("/setup", status_code=status.HTTP_200_OK)
async def setup_2fa(
    user_id: int = Depends(get_current_user_id),
    two_factor_service: TwoFactorService = Depends(TwoFactorService)
):
    """
    Generates a 2FA secret and QR code for the authenticated user.
    The user must verify this setup using the /verify endpoint.
    """
    return await two_factor_service.setup_2fa(user_id)


@router.post("/verify", status_code=status.HTTP_200_OK)
async def verify_2fa_setup(
    request: TwoFactorVerifyRequest,
    user_id: int = Depends(get_current_user_id),
    two_factor_service: TwoFactorService = Depends(TwoFactorService)
):
    """
    Verifies and enables 2FA for the user during setup.
    Requires the 2FA code generated by the authenticator app.
    """
    return await two_factor_service.verify_and_enable_2fa(user_id, request.code)


@router.post("/disable", status_code=status.HTTP_200_OK)
async def disable_2fa(
    user_id: int = Depends(get_current_user_id),
    two_factor_service: TwoFactorService = Depends(TwoFactorService)
):
    """
    Disables 2FA for the authenticated user.
    (In a real app, this might require password re-authentication).
    """
    return await two_factor_service.disable_2fa(user_id)
